test

diff --git a/.github/workflows/ci-scripted.yml b/.github/workflows/ci-scripted.yml
--- a/.github/workflows/ci-scripted.yml
+++ b/.github/workflows/ci-scripted.yml
@@ -201,6 +201,8 @@ jobs:
         $env:TF_VAR_workflow_sp_application_secret = $servicePrincipal.clientSecret
         $env:TF_VAR_workflow_sp_object_id = $servicePrincipal.objectId
         
+        # List environment variables
+        Get-ChildItem -Path Env: -Recurse -Include ARM_*,AZURE_*,GITHUB_*,INPUT_*,TF_* | Sort-Object -Property Name
         # Save environment variable setup for subsequent steps
         Get-ChildItem -Path Env: -Recurse -Include ARM_* | ForEach-Object {Write-Output "$($_.Name)=$($_.Value)"} >> $env:GITHUB_ENV
         foreach ($tfvar in $(Get-ChildItem -Path Env: -Recurse -Include TF_VAR_*)) {
@@ -213,97 +215,101 @@ jobs:
             Write-Output "${terraformVariableName}=`"${terraformVariableValue}`"" >> $env:GITHUB_ENV
           }
         } 
+      shell: pwsh
+
+    - name: Show environment variables
+      run: | 
         # List environment variables
         Get-ChildItem -Path Env: -Recurse -Include ARM_*,AZURE_*,GITHUB_*,INPUT_*,TF_* | Sort-Object -Property Name
       shell: pwsh
 
-    - name: Terraform Init & Plan
-      run: ./deploy.ps1 -Init -Plan
-      shell: pwsh
+    # - name: Terraform Init & Plan
+    #   run: ./deploy.ps1 -Init -Plan
+    #   shell: pwsh
         
-    - name: Use Node.js
-      if: ${{ matrix.terraform_apply }}
-      uses: actions/setup-node@v1
-    - name: Install Azure Functions Core Tools
-      if: ${{ matrix.terraform_apply }}
-      run: 
-        npm i -g azure-functions-core-tools@3 --unsafe-perm true
+    # - name: Use Node.js
+    #   if: ${{ matrix.terraform_apply }}
+    #   uses: actions/setup-node@v1
+    # - name: Install Azure Functions Core Tools
+    #   if: ${{ matrix.terraform_apply }}
+    #   run: 
+    #     npm i -g azure-functions-core-tools@3 --unsafe-perm true
         
-    - name: Terraform Apply
-      id: terraform-apply
-      if: ${{ matrix.terraform_apply }}
-      run: ./deploy.ps1 -Apply -Force -NoCode
-      shell: pwsh
+    # - name: Terraform Apply
+    #   id: terraform-apply
+    #   if: ${{ matrix.terraform_apply }}
+    #   run: ./deploy.ps1 -Apply -Force -NoCode
+    #   shell: pwsh
 
-    - name: Deploy Azure Function
-      if: ${{ matrix.terraform_apply }}
-      run: ./deploy_functions.ps1
-      shell: pwsh
+    # - name: Deploy Azure Function
+    #   if: ${{ matrix.terraform_apply }}
+    #   run: ./deploy_functions.ps1
+    #   shell: pwsh
 
-    - name: Test connection to Minecraft Server
-      if: ${{ matrix.terraform_apply }}
-      run: | 
-        Set-Location (Join-Path $env:GITHUB_WORKSPACE terraform) # Task does not support 'working-directory' property
-        $minecraftConfig  = (terraform output -json minecraft_java | ConvertFrom-Json -AsHashtable)
-        foreach ($minecraftConfigName in $minecraftConfig.Keys) {
-          Write-Host "Processing configuration '{$minecraftConfigName}''..."
-          $containerGroupID = $minecraftConfig[$minecraftConfigName].container_group_id
-          $serverFQDN       = $minecraftConfig[$minecraftConfigName].minecraft_server_fqdn
-          $serverPort       = $minecraftConfig[$minecraftConfigName].minecraft_server_port
+    # - name: Test connection to Minecraft Server
+    #   if: ${{ matrix.terraform_apply }}
+    #   run: | 
+    #     Set-Location (Join-Path $env:GITHUB_WORKSPACE terraform) # Task does not support 'working-directory' property
+    #     $minecraftConfig  = (terraform output -json minecraft_java | ConvertFrom-Json -AsHashtable)
+    #     foreach ($minecraftConfigName in $minecraftConfig.Keys) {
+    #       Write-Host "Processing configuration '{$minecraftConfigName}''..."
+    #       $containerGroupID = $minecraftConfig[$minecraftConfigName].container_group_id
+    #       $serverFQDN       = $minecraftConfig[$minecraftConfigName].minecraft_server_fqdn
+    #       $serverPort       = $minecraftConfig[$minecraftConfigName].minecraft_server_port
 
-          # Wait for Minecraft socket to open
-          $connectionAttempts = 0
-          do {
-            Start-Sleep -Seconds 10
-            Write-Host "Pinging ${serverFQDN} on port ${serverPort}..."
-            try {
-              $connectionAttempts++
-              $mineCraftConnection = New-Object System.Net.Sockets.TcpClient($serverFQDN, $serverPort) -ErrorAction SilentlyContinue
-            } catch [System.Management.Automation.MethodInvocationException] {
-              Write-Warning $_
-            }
-          } while ((!$mineCraftConnection || !$mineCraftConnection.Connected) -and ($connectionAttempts -le 10))
-          if ($mineCraftConnection.Connected) {
-              Write-Host "Connected to ${serverFQDN}:${serverPort}"
-              $mineCraftConnection.Close()
-          } else {
-              Write-Warning "Could not connect to ${serverFQDN}:${serverPort}!"
-          }
+    #       # Wait for Minecraft socket to open
+    #       $connectionAttempts = 0
+    #       do {
+    #         Start-Sleep -Seconds 10
+    #         Write-Host "Pinging ${serverFQDN} on port ${serverPort}..."
+    #         try {
+    #           $connectionAttempts++
+    #           $mineCraftConnection = New-Object System.Net.Sockets.TcpClient($serverFQDN, $serverPort) -ErrorAction SilentlyContinue
+    #         } catch [System.Management.Automation.MethodInvocationException] {
+    #           Write-Warning $_
+    #         }
+    #       } while ((!$mineCraftConnection || !$mineCraftConnection.Connected) -and ($connectionAttempts -le 10))
+    #       if ($mineCraftConnection.Connected) {
+    #           Write-Host "Connected to ${serverFQDN}:${serverPort}"
+    #           $mineCraftConnection.Close()
+    #       } else {
+    #           Write-Warning "Could not connect to ${serverFQDN}:${serverPort}!"
+    #       }
           
-          # BUG: https://github.com/Azure/azure-cli/issues/19475
-          if ([version]$(az version --query '\"azure-cli\"' -o tsv) -ge [version]"2.29") {
-            # BUG: https://github.com/Azure/azure-cli/issues/13352
-            #      No tty / ioctl device
-            # az container exec --ids $containerGroupID --exec-command "/health.sh" --container-name minecraft
-            script --return --quiet -c "az container exec --ids $containerGroupID --exec-command '/health.sh' --container-name minecraft" /dev/null
+    #       # BUG: https://github.com/Azure/azure-cli/issues/19475
+    #       if ([version]$(az version --query '\"azure-cli\"' -o tsv) -ge [version]"2.29") {
+    #         # BUG: https://github.com/Azure/azure-cli/issues/13352
+    #         #      No tty / ioctl device
+    #         # az container exec --ids $containerGroupID --exec-command "/health.sh" --container-name minecraft
+    #         script --return --quiet -c "az container exec --ids $containerGroupID --exec-command '/health.sh' --container-name minecraft" /dev/null
 
-            az container show --ids $containerGroupID --query instanceView
-            az container logs --ids $containerGroupID
-          }
-        }
-      shell: pwsh
+    #         az container show --ids $containerGroupID --query instanceView
+    #         az container logs --ids $containerGroupID
+    #       }
+    #     }
+    #   shell: pwsh
 
-    - name: Remove backup items & resource locks
-      if: ${{ matrix.destroy }}
-      run: | 
-        . (Join-Path $env:GITHUB_WORKSPACE scripts functions.ps1)
-        TearDown-Resources -Backups -Locks
-      shell: pwsh
+    # - name: Remove backup items & resource locks
+    #   if: ${{ matrix.destroy }}
+    #   run: | 
+    #     . (Join-Path $env:GITHUB_WORKSPACE scripts functions.ps1)
+    #     TearDown-Resources -Backups -Locks
+    #   shell: pwsh
 
-    - name: Terraform Destroy
-      if: ${{ matrix.destroy }}
-      run: ./deploy.ps1 -Destroy -Force
-      shell: pwsh
-      continue-on-error: false
+    # - name: Terraform Destroy
+    #   if: ${{ matrix.destroy }}
+    #   run: ./deploy.ps1 -Destroy -Force
+    #   shell: pwsh
+    #   continue-on-error: false
 
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v2
-      if: ${{ matrix.terraform_apply }}
-      with:
-        name: terraform
-        path: 'terraform'
+    # - name: Upload artifacts
+    #   uses: actions/upload-artifact@v2
+    #   if: ${{ matrix.terraform_apply }}
+    #   with:
+    #     name: terraform
+    #     path: 'terraform'
       
-    - name: Teardown
-      if: ${{ matrix.destroy || failure() }}
-      run: ./deploy.ps1 -Init -Teardown
-      shell: pwsh
+    # - name: Teardown
+    #   if: ${{ matrix.destroy || failure() }}
+    #   run: ./deploy.ps1 -Init -Teardown
+    #   shell: pwsh
