Use netcat to wait for minecraft

diff --git a/.github/workflows/ci-vanilla.yml b/.github/workflows/ci-vanilla.yml
--- a/.github/workflows/ci-vanilla.yml
+++ b/.github/workflows/ci-vanilla.yml
@@ -112,30 +112,32 @@ jobs:
         errorActionPreference: Stop
         failOnStandardError: true
 
-    - name: Test connection to Minecraft Server
-      uses: Azure/powershell@v1
-      env:
-        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
-      with:
-        inlineScript: | 
-          # List environment variables
-          Get-ChildItem -Path Env: -Recurse -Include ARM_*,AZURE_*,GITHUB_*,TF_* | Sort-Object -Property Name
+    # - name: Test connection to Minecraft Server
+    #   uses: Azure/powershell@v1
+    #   env:
+    #     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
+    #   with:
+    #     inlineScript: | 
+    #       # List environment variables
+    #       Get-ChildItem -Path Env: -Recurse -Include ARM_*,AZURE_*,GITHUB_*,TF_* | Sort-Object -Property Name
 
-          # Start-Sleep -Seconds 120 # Wait for Minecraft to boot up
-          az container exec --ids ${{ steps.terraform-apply.outputs.container_group_id }}--exec-command "rcon-cli say hello from ci"
-        azPSVersion: latest
-        errorActionPreference: Stop
-        failOnStandardError: true # BUG: setting not honored
+    #       # Start-Sleep -Seconds 120 # Wait for Minecraft to boot up
+    #       az container exec --ids ${{ steps.terraform-apply.outputs.container_group_id }} --exec-command "rcon-cli say hello from ci"
+    #     azPSVersion: latest
+    #     errorActionPreference: Stop
+    #     failOnStandardError: true # BUG: setting not honored
 
-    - name: Test connection to Minecraft Server (CLI)
+    - name: Test connection to Minecraft Server (bash)
       uses: Azure/CLI@v1
       env:
         AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
       with:
         inlineScript: | 
           printenv | sort
-          sleep 120 # Wait for Minecraft to boot up
-          echo "az container exec --ids $TF_OUT_container_group_id"
+          # Wait for Minecraft to boot up
+          # sleep 120 
+          while ! echo exit | nc $TF_OUT_minecraft_server_fqdn $TF_OUT_minecraft_server_port; do sleep 10; done
+          echo "az container exec --ids ${{ steps.terraform-apply.outputs.container_group_id }}"
           az container exec --ids $TF_OUT_container_group_id --exec-command "rcon-cli say hello from ci"
 
     - name: Terraform Destroy
